# Generated by Django 2.2 on 2021-11-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.RegionalLeague')),
                ('runnerup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_runner_up', to='team.Team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rl_winner', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='NationalLeagueAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nl_winner', to='team.Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.NationalLeague')),
                ('second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nl_second', to='team.Team')),
                ('third', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nl_third', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionsLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('runnerup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_runner_up', to='team.Team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_winner', to='team.Team')),
            ],
        ),
    ]
