# Generated by Django 2.2 on 2021-11-09 10:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2),
            preserve_default=False,
        ),
    ]
